version: '3.6'
services:
  ssl-webgateway:
    image: ssl-webgateway:latest
    container_name: ssl-webgateway
    ports: 
      - "80:80"
      - "443:443"
    environment:
      - ISC_DATA_DIRECTORY=/durable/webgateway
      - IRIS_USER=CSPsystem
      - IRIS_PASSWORD=SYS
      - IRIS_HOST=iris
      - IRIS_PORT=51773
      - IRIS_WEBAPPS=/irisapp1 /irisapp2 /irisapp3
      - APACHE_SERVER_ADMIN=webmaster@example.com
      - APACHE_SERVER_NAME=example.com
      - APACHE_SERVER_ALIAS=www.example.com
      - LETSENCRYPT_WEBROOT=/var/www/example
      - LETSENCRYPT_DOMAIN=-d example.com -d www.example.com
      - LETSENCRYPT_ARGS=--test-cert
    volumes:
      - "webgateway:/durable"
      - "letsencrypt:/etc/letsencrypt"
    command: ["sh /startUpScript.sh"]
  iris:
    image: intersystemsdc/iris-community:2020.2.0.196.0-zpm
volumes:
  webgateway:
    external: true
    name: "webgateway"
  letsencrypt:
    external: true
    name: "letsencrypt"